# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nlink_parser/IotFrame0Node.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class IotFrame0Node(genpy.Message):
  _md5sum = "18c74fd1a18895f584bf54c3563d0a60"
  _type = "nlink_parser/IotFrame0Node"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 uid
uint8 cnt
float32 dis
float32 aoa_angle_horizontal
float32 aoa_angle_vertical
"""
  __slots__ = ['uid','cnt','dis','aoa_angle_horizontal','aoa_angle_vertical']
  _slot_types = ['uint32','uint8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       uid,cnt,dis,aoa_angle_horizontal,aoa_angle_vertical

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IotFrame0Node, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.uid is None:
        self.uid = 0
      if self.cnt is None:
        self.cnt = 0
      if self.dis is None:
        self.dis = 0.
      if self.aoa_angle_horizontal is None:
        self.aoa_angle_horizontal = 0.
      if self.aoa_angle_vertical is None:
        self.aoa_angle_vertical = 0.
    else:
      self.uid = 0
      self.cnt = 0
      self.dis = 0.
      self.aoa_angle_horizontal = 0.
      self.aoa_angle_vertical = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IB3f().pack(_x.uid, _x.cnt, _x.dis, _x.aoa_angle_horizontal, _x.aoa_angle_vertical))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.uid, _x.cnt, _x.dis, _x.aoa_angle_horizontal, _x.aoa_angle_vertical,) = _get_struct_IB3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IB3f().pack(_x.uid, _x.cnt, _x.dis, _x.aoa_angle_horizontal, _x.aoa_angle_vertical))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.uid, _x.cnt, _x.dis, _x.aoa_angle_horizontal, _x.aoa_angle_vertical,) = _get_struct_IB3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IB3f = None
def _get_struct_IB3f():
    global _struct_IB3f
    if _struct_IB3f is None:
        _struct_IB3f = struct.Struct("<IB3f")
    return _struct_IB3f
